---
deployment:
  tasks:
    - export DEPLOYPATH=/home/foxinfoh/ingatlanfox_laravel7/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp  server.php $DEPLOYPATH











